name: learn-github-actions

on:
 push:
    branches:
      - stag
      - main
      - development
jobs:
  check-bats-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
